# Setup the environment:
sudo: false
dist: trusty
cache: bundler

# Setup the compiler:
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-4.0
    packages:
      - clang-4.0
      - libc++-dev
      - libc++abi-dev

env: CC=clang-4.0 CXX=clang++-4.0

# Install required gems:
install:
  - rvm use 2.4 --install --binary --fuzzy
  - gem install teapot --version 2.0.0-rc3

# Run tests:
script:
  - teapot fetch
  - teapot build Test/Concurrent
